# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toad < Formula
  desc "AI-powered code assistant that lives in Slack"
  homepage "https://github.com/cdre-ai/toad"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.0/toad_0.1.0_darwin_amd64.tar.gz"
      sha256 "bc8d184c1461264c08048b81a9139dbb49eb1d867e4d298505a28f87556002ec"

      define_method(:install) do
        bin.install "toad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.0/toad_0.1.0_darwin_arm64.tar.gz"
      sha256 "b04d51f9ac91a398f6e03579e8c9b79593550324b4813ca6b981a7094cbaa520"

      define_method(:install) do
        bin.install "toad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.0/toad_0.1.0_linux_amd64.tar.gz"
      sha256 "93c0234adb85a86a9f02241a61f52f41bdcf531710192305c171b448696cc17b"
      define_method(:install) do
        bin.install "toad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.0/toad_0.1.0_linux_arm64.tar.gz"
      sha256 "be72bfe3201f2395a9047689fc3d6152cc0030359e0ded55690225f198302e0b"
      define_method(:install) do
        bin.install "toad"
      end
    end
  end

  test do
    system "#{bin}/toad", "version"
  end
end
