# This file was generated by GoReleaser. DO NOT EDIT.
cask "toad" do
  name "toad"
  desc "AI-powered code assistant that lives in Slack"
  homepage "https://github.com/cdre-ai/toad"
  version "0.1.48"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toad"

  on_macos do
    on_intel do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_macOS_64bit.tar.gz"
      sha256 "03097d0e2c617c8f65ae0dbfea12529842ad4f107a44a922c4a72851005fb77d"
    end
    on_arm do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_macOS_ARM64.tar.gz"
      sha256 "613e9c02d0fa58c01f2474e7cf1a8e53663057b22b89899b4865576b66901603"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_Linux_64bit.tar.gz"
      sha256 "3d0a22832eec884977ced300f3a3bb649409215a48aa9a598c5545fdbe0a9c70"
    end
    on_arm do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_Linux_ARM64.tar.gz"
      sha256 "5dea5e1a4414f97bc2b20b422348b32fd4bd8e81613f6ee5da81dadb9bee8a7f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toad"]
    end
  end

  caveats do
    "run 'toad --help' to get started"
  end

  # No zap stanza required
end
