# This file was generated by GoReleaser. DO NOT EDIT.
cask "toad" do
  name "toad"
  desc "AI-powered code assistant that lives in Slack"
  homepage "https://github.com/cdre-ai/toad"
  version "0.1.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toad"

  on_macos do
    on_intel do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_macOS_64bit.tar.gz"
      sha256 "a964de22554626c4f5b4306926d42b45d100b262e84121a7d673ec3798031cca"
    end
    on_arm do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_macOS_ARM64.tar.gz"
      sha256 "959150a931fb63d8c3d41cc6a44137d5dfdc190d08469c5bb201b9dc6cf0df8d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_Linux_64bit.tar.gz"
      sha256 "aafeab7decbeeb1cd097e7e3c880dd71f10e26ade35aeb1d6454049090a5f71b"
    end
    on_arm do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_Linux_ARM64.tar.gz"
      sha256 "8db07bc44e6c7e78b3fdc6a816dfb47ae6b831638f71e871b678d4642d075958"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toad"]
    end
  end

  caveats do
    "run 'toad --help' to get started"
  end

  # No zap stanza required
end
