# This file was generated by GoReleaser. DO NOT EDIT.
cask "toad" do
  name "toad"
  desc "AI-powered code assistant that lives in Slack"
  homepage "https://github.com/cdre-ai/toad"
  version "0.1.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toad"

  on_macos do
    on_intel do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_macOS_64bit.tar.gz"
      sha256 "743216d123f2d36e301db385e5ec82a3f05b8face03d155a91d77e5754321fe3"
    end
    on_arm do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_macOS_ARM64.tar.gz"
      sha256 "963ff35cd7618a4753302ca29496715d5eea0b0fa350eeba27ae5fb0ed3d89a6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_Linux_64bit.tar.gz"
      sha256 "a4b289b160cc551ce94cbbae64f4095c38b7df07638fd4851d4bac2bc19c8b34"
    end
    on_arm do
      url "https://github.com/cdre-ai/toad/releases/download/v#{version}/toad_v#{version}_Linux_ARM64.tar.gz"
      sha256 "53984f03de00e4fc88e84c4f6e263e4b5b1c0d4be672d6fada511a3f1eb79056"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toad"]
    end
  end

  caveats do
    "run 'toad --help' to get started"
  end

  # No zap stanza required
end
