# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cadre < Formula
  desc "A foreman for Claude Code — supervises permissions, reviews code, runs quality gates"
  homepage "https://github.com/cdre-ai/cadre-releases"
  version "0.1.0-beta.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cdre-ai/cadre-releases/releases/download/v0.1.0-beta.15/cadre-releases_0.1.0-beta.15_darwin_amd64.tar.gz"
      sha256 "8512d432c4f281e2e77d8dea8c1557fd7fa79ffe5be08eecd636a5020b3b4d77"

      def install
        bin.install "cadre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cdre-ai/cadre-releases/releases/download/v0.1.0-beta.15/cadre-releases_0.1.0-beta.15_darwin_arm64.tar.gz"
      sha256 "6b4874e1a3095744a05a7bef72d0c1ce59ea6115d2eff387a098bb4d30430b2c"

      def install
        bin.install "cadre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdre-ai/cadre-releases/releases/download/v0.1.0-beta.15/cadre-releases_0.1.0-beta.15_linux_amd64.tar.gz"
      sha256 "059e9a0713d1c7547a056bc16762e55547e1605867ccca4b2b0b535eb1467937"
      def install
        bin.install "cadre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdre-ai/cadre-releases/releases/download/v0.1.0-beta.15/cadre-releases_0.1.0-beta.15_linux_arm64.tar.gz"
      sha256 "4b9d78928bed323e87accaf5e532bfc447304b72aa4a58ab508139db47201234"
      def install
        bin.install "cadre"
      end
    end
  end

  test do
    assert_match "cadre", shell_output("#{bin}/cadre version 2>&1")
  end
end
