# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CadreReleases < Formula
  desc "A foreman for Claude Code — supervises permissions, reviews code, runs quality gates"
  homepage "https://github.com/cdre-ai/cadre-releases"
  version "0.1.0-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cdre-ai/cadre-releases/releases/download/v0.1.0-beta.1/cadre-releases_0.1.0-beta.1_darwin_amd64.tar.gz"
      sha256 "3f84fbf7b3f0b81fd75f03b38234bf307a9ba3c3da7ca6f5c84a425ce4d2b3c5"

      def install
        bin.install "cadre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cdre-ai/cadre-releases/releases/download/v0.1.0-beta.1/cadre-releases_0.1.0-beta.1_darwin_arm64.tar.gz"
      sha256 "9de8e550b2c41b0fcec04157dbf44b699fb8a5df6df4df8fe21c53f32d2b0f48"

      def install
        bin.install "cadre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdre-ai/cadre-releases/releases/download/v0.1.0-beta.1/cadre-releases_0.1.0-beta.1_linux_amd64.tar.gz"
      sha256 "419bf23a70b1aeaa83d012f8ae54e3f6ca7523474fed2b1f9847f8182cffbd3f"
      def install
        bin.install "cadre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdre-ai/cadre-releases/releases/download/v0.1.0-beta.1/cadre-releases_0.1.0-beta.1_linux_arm64.tar.gz"
      sha256 "69a6d437ba026ecff40e59853f3cf45bfc3e36b90ea49378ea66ab2eb7128eac"
      def install
        bin.install "cadre"
      end
    end
  end

  test do
    assert_match "cadre", shell_output("#{bin}/cadre version 2>&1")
  end
end
