# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toad < Formula
  desc "AI-powered code assistant that lives in Slack"
  homepage "https://github.com/cdre-ai/toad"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.3/toad_0.1.3_darwin_amd64.tar.gz"
      sha256 "de7fb4833bfce718dc1b095ce16c8929cfb62c93acab00dd9ba4ce5cdcd9251f"

      define_method(:install) do
        bin.install "toad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.3/toad_0.1.3_darwin_arm64.tar.gz"
      sha256 "c95c9305b41d1fb062d92d2718ff7812c8a3e7cb6b053e6806b7e8ea9d9fc158"

      define_method(:install) do
        bin.install "toad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.3/toad_0.1.3_linux_amd64.tar.gz"
      sha256 "b1ae334786482687e0f555e6f56c4773972202374e739137dbe380047241b167"
      define_method(:install) do
        bin.install "toad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.3/toad_0.1.3_linux_arm64.tar.gz"
      sha256 "3e24b04b3b52addccbfe189d95d8ebc8a14c4ebcb64557bdab0cc70c5ac9ce85"
      define_method(:install) do
        bin.install "toad"
      end
    end
  end

  test do
    system "#{bin}/toad", "version"
  end
end
