# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toad < Formula
  desc "AI-powered code assistant that lives in Slack"
  homepage "https://github.com/cdre-ai/toad"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.2/toad_0.1.2_darwin_amd64.tar.gz"
      sha256 "d11463fa735c73e2756e541a443644891a20b51005182a4de6de301f52a79a2f"

      define_method(:install) do
        bin.install "toad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.2/toad_0.1.2_darwin_arm64.tar.gz"
      sha256 "ae6dd2729a3d364965b67df36ef9e363ea7f632e2dc0a03fa39ebef7441be9ca"

      define_method(:install) do
        bin.install "toad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.2/toad_0.1.2_linux_amd64.tar.gz"
      sha256 "8e4f7f88cdc558ef13455ef72d71ef8e3d70d1e7b6399c42ad0c472610f9ad76"
      define_method(:install) do
        bin.install "toad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdre-ai/toad/releases/download/v0.1.2/toad_0.1.2_linux_arm64.tar.gz"
      sha256 "f3d2c58f3aa47cb1967337c9f59387c74c24e092a1e5e7821fe2b5fbbd557b37"
      define_method(:install) do
        bin.install "toad"
      end
    end
  end

  test do
    system "#{bin}/toad", "version"
  end
end
